name: Publish Resume

on:
  push:
    branches: [ main ]   # or master, whichever branch you're using

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Show repo status before build
        run: |
          echo "Repo root contents before build:"
          ls -la
          echo "Git status:"
          git status

      - name: Download resume.json from gist
        run: |
          echo "Downloading resume.json from gist..."
          curl -L https://gist.githubusercontent.com/ranga-9/469874b1b4a22c7374c059b19a1cac0a/raw/resume.json -o resume.json
          echo "Downloaded resume.json:"
          head -n 20 resume.json || echo "resume.json not found"

      - name: Generate HTML with jsonresume-export
        uses: kelvintaywl/action-jsonresume-export@v1
        with:
          theme: macchiato
          resume_filepath: resume.json
          output_filepath: index.html   # root-level

      - name: Add _config.yml
        run: |
          echo "title: My Resume" > _config.yml
          echo "description: Resume site" >> _config.yml
          echo "theme: minima" >> _config.yml
          echo "exclude:" >> _config.yml
          echo "  - resume.json" >> _config.yml
          echo "  - .github" >> _config.yml
          echo "  - node_modules" >> _config.yml
          echo "  - package.json" >> _config.yml
          echo "  - package-lock.json" >> _config.yml
          echo "_config.yml created."

      - name: Debug generated files
        run: |
          echo "Listing root folder after generation:"
          ls -la
          echo "Preview of index.html:"
          head -n 20 index.html || echo "index.html missing"
          echo "Preview of _config.yml:"
          cat _config.yml

      - name: Commit built resume
        run: |
          echo "Staging files..."
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add index.html _config.yml
          echo "Git status after staging:"
          git status
          echo "Attempting commit..."
          git commit -m "[ci skip] Update resume HTML" || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
