name: Publish Resumes

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # Founder resume
      - name: Download founder resume.json
        run: |
          curl -L https://gist.githubusercontent.com/ranga-9/469874b1b4a22c7374c059b19a1cac0a/raw/resume.json -o resume-founder.json
          echo "Validating founder resume.json"
          jq . resume-founder.json

      - name: Generate Founder Resume
        uses: kelvintaywl/action-jsonresume-export@v1
        with:
          theme: elegant
          resume_filepath: resume-founder.json
          output_filepath: founder.html

      - name: Debug founder.html
        run: |
          echo "Checking founder.html..."
          ls -la founder.html || echo "founder.html missing"
          head -n 20 founder.html || echo "No preview"

      # Tech resume
      - name: Download tech resume.json
        run: |
          curl -L https://gist.github.com/ranga-9/3d9618b0fc2c21529d9bb349bc99a64d/raw/resume-2.json -o resume-tech.json
          echo "Validating tech resume.json"
          jq . resume-tech.json

      - name: Generate Tech Resume
        uses: kelvintaywl/action-jsonresume-export@v1
        with:
          theme: macchiato
          resume_filepath: resume-tech.json
          output_filepath: tech.html

      - name: Debug tech.html
        run: |
          echo "Checking tech.html..."
          ls -la tech.html || echo "tech.html missing"
          head -n 20 tech.html || echo "No preview"

      # Homepage linking both resumes
      - name: Create index.html
        run: |
          echo "<!DOCTYPE html><html><head><title>My Resumes</title></head><body>" > index.html
          echo "<h1>Choose a Resume</h1><ul>" >> index.html
          echo "<li><a href='founder.html'>Founder Resume</a></li>" >> index.html
          echo "<li><a href='tech.html'>Tech Resume</a></li>" >> index.html
          echo "</ul></body></html>" >> index.html

      # Jekyll config
      - name: Add _config.yml
        run: |
          echo "title: My Resumes" > _config.yml
          echo "description: Multiple resumes" >> _config.yml
          echo "theme: minima" >> _config.yml
          echo "exclude:" >> _config.yml
          echo "  - resume-*.json" >> _config.yml
          echo "  - .github" >> _config.yml

      # Commit & push
      - name: Commit built resumes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          # add all generated files safely
          git add *.html _config.yml || true
          git status
          git commit -m "[ci skip] Update resumes" || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
